#include "commacalc.h"

//NOTE FOR FUTURE ME: CONSIDER USING A NAMESPACE FOR GLOBAL HISTORY VARIABLE(S)

int main(){
	
	//START

	//PRINT INSTRUCTIONS
	printMenu();

	//READ INPUT STRING

	//CLEAR INPUT BUFFER

	//CHECK VALIDITY OF INPUT STRING LENGTH

	//CHECK FOR "EXIT" (ANY CASE) -> BREAK

	//CHECK FOR "HISTORY" (ANY CASE) -> PRINT LAST 5 EXPRESSIONS AND RESULTS -> LOOP TO START

	//PARSE EXPRESSION FROM STRING

	//CHECK VALIDITY OF INPUT STRING EXPRESSION

	//FORMAT STRING FOR SIMPLE PARSING

	//EVALUATE EXPRESSION
	
	//OUTPUT RESULT

	//STORE EXPRESSION AND RESULT IN HISTORY

	//LOOP TO START
	
	return 0;
}
